// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnvbcyquwsvfjxprbnhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1udmJjeXF1d3N2Zmp4cHJibmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDg5MTksImV4cCI6MjA2Nzg4NDkxOX0._qEtAMsg7y3X1g7ASF5i-yfAUx0pgYBwZvET5RJ4O1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});